spring:
  profiles:
    active: @profileActive@

server:
  tomcat:
    uri-encoding: UTF-8
    max-http-header-size: 65536
  servlet:
    context-path: /micro-controller
    max-http-header-size: 65536
    multipart:
          max-file-size: 15MB
          max-request-size: 20MB

my:
  service:
    version: 1.0.0
