spring:
  dubbo:
      application:
        name: controller-consumer # 本服务的名称
      registry:
        address: zookeeper://192.168.109.128:2181
      scan: com.jeff.controller
  redis:
    host: 123.207.253.82
    port: 7481
    database: 6
    password: 1234567890
    jedis:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms